export const COLLECTIONS = {
  clinicas: "clinicas",
  especialidades: "especialidades",
  boxes: "boxes",
  profesionales: "profesionales",
  pacientes: "pacientes",
  usuarios: "usuarios",
  citas: "citas",
  presupuestos: "presupuestos",
  caja: "caja",
  banners: "banners",
  destacados: "destacados",
  alianzas: "alianzas",
  testimonios: "testimonios",
} as const;
